---
- name: Update apt
  apt: >
    update_cache=yes
    cache_valid_time=3600

- name: Install deps
  apt: >
    pkg={{item}}
    state=installed
  with_items:
    - unzip
    - jq

- name: Download consul
  get_url: >
    url={{consul_download}}
    dest={{consul_download_folder}}
  register: consul_was_downloaded

- name: Create consul directory
  file: >
    state=directory
    path={{ item }}
  with_items:
    - "{{ consul_home }}"
    - "{{ consul_home }}/data"
    - "{{ consul_home }}/bin"
    - "{{ consul_config_dir }}"

- name: Copy and unpack
  unarchive: >
    src={{ consul_download_folder }}/{{ consul_archive }}
    dest={{ consul_home }}/bin
    copy=no
  when: consul_was_downloaded|changed

- name: Create consul group
  group: >
    name={{consul_group}}
    state=present

- name: Create consul user
  user: >
    name={{consul_user}}
    group={{consul_group}}

- name: Set file ownership
  file: >
    state=directory
    path={{consul_home}}
    owner={{consul_user}}
    group={{consul_group}}
    recurse=yes
  when: consul_was_downloaded|changed

- name: Copy consul upstart script
  template: >
    src=consul.conf.j2
    dest=/etc/init/consul.conf
    owner={{consul_user}}
    group={{consul_group}}
    mode=0755

- name: Add consul to path through profile.d
  template: >
    src=consul.sh.j2
    dest=/etc/profile.d/consul.sh
    owner=root
    group=root
    mode=0755

- name: Copy consulkv script
  template: >
    src=consulkv.j2
    dest={{consul_home}}/bin/consulkv
    owner={{consul_user}}
    group={{consul_group}}
    mode=0755

- name: Add consul config file
  template: >
    src=consul.json.j2
    dest={{ consul_config_file }}
    owner={{consul_user}}
    group={{consul_group}}
    mode=0755
  notify: Restart consul

